version: '3.8'

services:
  grass-grid-platform:
    build: .
    container_name: grass-grid-platform
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      # 如果需要持久化日志，可以取消注释下面的行
      # - ./logs:/var/log/nginx
    networks:
      - grass-grid-network

networks:
  grass-grid-network:
    driver: bridge
